version: "3.8"

services:
  scraper:
    build: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: supersecretpassword
      MYSQL_DATABASE: moviesmod
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysqldata:/var/lib/mysql
    healthcheck: 
      test: ["CMD-SHELL", "mysql -h localhost -u root -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  mysqldata: